# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# Spring配置
spring:
  application:
    name: judge-service
  # MongoDB配置
  mail:
    host: smtp.qq.com
    port: 587
    username: ********
    password: ********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    from: ********
    default-encoding: utf-8
    smtp:
      auth: true
  data:
    mongodb:
      uri: mongodb://********:27017/judge_db
      password: '********'
      username: ********
      auto-index-creation: true
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器地址
      host: ********
      password: ********
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  # MySQL配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://********:3306/judge_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ********
    password: ********
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 获取连接等待超时的时间(毫秒)
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接(毫秒)
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间(毫秒)
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间(毫秒)
      max-evictable-idle-time-millis: 900000
      # 用来测试连接是否可用的查询语句
      validation-query: SELECT 1
      # 建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

# 日志配置
logging:
  level:
    root: INFO
    com.trae.judge: DEBUG
    org.springframework.data.mongodb: INFO

# Swagger/OpenAPI配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.trae.judge.controller

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dong.judge.model

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # JWT密钥
  jwt-secret-key: adong
  # token前缀
  token-prefix: Bearer

# 文件存储配置
file:
  upload:
    dir: uploads
  storage:
    type: local

# 云存储配置
cloud:
  storage:
    aliyun:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      accessKeyId: your-access-key-id
      accessKeySecret: your-access-key-secret
      bucketName: your-bucket-name
    tencent:
      secretId: your-secret-id
      secretKey: your-secret-key
      region: ap-guangzhou
      bucketName: your-bucket-name

sandbox:
  api:
    url: http://sandbox:5050